### ISSUE TITLE
Bugs and todo

### ISSUE THREAD

**Issue by BrettRToomey** [kai-language/kai#24]
Here is a TODO list and a place where we can report bugs and their current status. Feel free to update this if you find anything @vdka @Joannis

## Features/Quality of life
- [x] Coercion between arrays and pointers
- [x] Maybe some coercion between `string`s and arrays
  - [x] Decide if this is allowed implicitly. @vdka thoughts?
- [x] Implicit sized array declaration (`buffer: []i8 = {0, 0, 0, 0}`)

## Checker
- [ ] Default values for all types

## 🐛s
- [X] failure to parse empty blocks
- [x] `else { if { //...` and `else if { //...` generate invalid IR
- [x] The following generates an error:

```
  6 in_addr :: struct {
  7     s_addr : u32
  8 }
  9 
 10 sockaddr_in :: struct {
 11     sin_len : u8
 12     sa_family_t : u8
 13     sin_port_t : u16
 14     sin_addr: in_addr
 15     sin_zero: [8]i8
 16 }
 // ...
    bindAddr : in_addr = {0}
```

```
ERROR(server.kai:42:28): Unexpected statement, expected expression
    raised by /Users/bretttoomey/Documents/kai/Sources/kai/Checker.swift:1559

ERROR(server.kai:42:18): Cannot implicitly convert type '<invalid>' to type 'in_addr :: struct { s_addr: u32 }'
    raised by /Users/bretttoomey/Documents/kai/Sources/kai/Checker.swift:1095

ERROR(server.kai:47:27): Cannot convert '<invalid>' to expected type 'in_addr :: struct { s_addr: u32 }'
    raised by /Users/bretttoomey/Documents/kai/Sources/kai/Checker.swift:1606
```

- [x] Unconstrained Integer Conversion failing for array subscripts
  - ```
        for i : u8 = 0; i < 16; i += 1 {
            <buf[int(i)] = i
        }
    ```

  - Without explicit casts the above fails

**Comment by BrettRToomey** [comment]
Closing for now.
